In [1]:
pip install faker

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: faker in /global/home/hpc3552/.local/lib/python3.6/site-packages (13.15.0)
Requirement already satisfied: typing-extensions>=3.10.0.2 in /global/home/hpc3552/.local/lib/python3.6/site-packages (from faker) (4.1.1)
Requirement already satisfied: python-dateutil>=2.4 in /opt/python/anaconda3/lib/python3.6/site-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/python/anaconda3/lib/python3.6/site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import datetime
import random
from faker import Faker

In [3]:
fake = Faker()
Faker.seed(42)
random.seed(42)

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/stepthom/869_course/main/data/GermanCredit.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 62 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Duration                                1000 non-null   int64
 1   Amount                                  1000 non-null   int64
 2   InstallmentRatePercentage               1000 non-null   int64
 3   ResidenceDuration                       1000 non-null   int64
 4   Age                                     1000 non-null   int64
 5   NumberExistingCredits                   1000 non-null   int64
 6   NumberPeopleMaintenance                 1000 non-null   int64
 7   Telephone                               1000 non-null   int64
 8   ForeignWorker                           1000 non-null   int64
 9   Class                                   1000 non-null   object
 10  CheckingAccountStatus.lt.0              1000 non-null   int64
 11  CheckingAccountStatus.0.to.200          1000 non-null   int64
 12  CheckingAccountStatus.gt.200            1000 non-null   int64
 13  CheckingAccountStatus.none              1000 non-null   int64
 14  CreditHistory.NoCredit.AllPaid          1000 non-null   int64
 15  CreditHistory.ThisBank.AllPaid          1000 non-null   int64
 16  CreditHistory.PaidDuly                  1000 non-null   int64
 17  CreditHistory.Delay                     1000 non-null   int64
 18  CreditHistory.Critical                  1000 non-null   int64
 19  Purpose.NewCar                          1000 non-null   int64
 20  Purpose.UsedCar                         1000 non-null   int64
 21  Purpose.Furniture.Equipment             1000 non-null   int64
 22  Purpose.Radio.Television                1000 non-null   int64
 23  Purpose.DomesticAppliance               1000 non-null   int64
 24  Purpose.Repairs                         1000 non-null   int64
 25  Purpose.Education                       1000 non-null   int64
 26  Purpose.Vacation                        1000 non-null   int64
 27  Purpose.Retraining                      1000 non-null   int64
 28  Purpose.Business                        1000 non-null   int64
 29  Purpose.Other                           1000 non-null   int64
 30  SavingsAccountBonds.lt.100              1000 non-null   int64
 31  SavingsAccountBonds.100.to.500          1000 non-null   int64
 32  SavingsAccountBonds.500.to.1000         1000 non-null   int64
 33  SavingsAccountBonds.gt.1000             1000 non-null   int64
 34  SavingsAccountBonds.Unknown             1000 non-null   int64
 35  EmploymentDuration.lt.1                 1000 non-null   int64
 36  EmploymentDuration.1.to.4               1000 non-null   int64
 37  EmploymentDuration.4.to.7               1000 non-null   int64
 38  EmploymentDuration.gt.7                 1000 non-null   int64
 39  EmploymentDuration.Unemployed           1000 non-null   int64
 40  Personal.Male.Divorced.Seperated        1000 non-null   int64
 41  Personal.Female.NotSingle               1000 non-null   int64
 42  Personal.Male.Single                    1000 non-null   int64
 43  Personal.Male.Married.Widowed           1000 non-null   int64
 44  Personal.Female.Single                  1000 non-null   int64
 45  OtherDebtorsGuarantors.None             1000 non-null   int64
 46  OtherDebtorsGuarantors.CoApplicant      1000 non-null   int64
 47  OtherDebtorsGuarantors.Guarantor        1000 non-null   int64
 48  Property.RealEstate                     1000 non-null   int64
 49  Property.Insurance                      1000 non-null   int64
 50  Property.CarOther                       1000 non-null   int64
 51  Property.Unknown                        1000 non-null   int64
 52  OtherInstallmentPlans.Bank              1000 non-null   int64
 53  OtherInstallmentPlans.Stores            1000 non-null   int64
 54  OtherInstallmentPlans.None              1000 non-null   int64
 55  Housing.Rent                            1000 non-null   int64
 56  Housing.Own                             1000 non-null   int64
 57  Housing.ForFree                         1000 non-null   int64
 58  Job.UnemployedUnskilled                 1000 non-null   int64
 59  Job.UnskilledResident                   1000 non-null   int64
 60  Job.SkilledEmployee                     1000 non-null   int64
 61  Job.Management.SelfEmp.HighlyQualified  1000 non-null   int64
dtypes: int64(61), object(1)
memory usage: 484.5+ KB

In [5]:
today = datetime.date(2021, 6, 1)
print(today)

2021-06-01

In [6]:
dob = today - datetime.timedelta(days=40*365)
print(dob)

1981-06-11

In [7]:
df.head()

,Duration,Amount,InstallmentRatePercentage,ResidenceDuration,Age,NumberExistingCredits,NumberPeopleMaintenance,Telephone,ForeignWorker,Class,...,OtherInstallmentPlans.Bank,OtherInstallmentPlans.Stores,OtherInstallmentPlans.None,Housing.Rent,Housing.Own,Housing.ForFree,Job.UnemployedUnskilled,Job.UnskilledResident,Job.SkilledEmployee,Job.Management.SelfEmp.HighlyQualified
0,6,1169,4,4,67,2,1,0,1,Good,...,0,0,1,0,1,0,0,0,1,0
1,48,5951,2,2,22,1,1,1,1,Bad,...,0,0,1,0,1,0,0,0,1,0
2,12,2096,2,3,49,1,2,1,1,Good,...,0,0,1,0,1,0,0,1,0,0
3,42,7882,2,4,45,1,2,1,1,Good,...,0,0,1,0,0,1,0,0,1,0
4,24,4870,3,4,53,2,2,1,1,Bad,...,0,0,1,0,0,1,0,0,1,0

In [8]:
#Generate 20 random cities:
n = 20
cities = [fake.city() for _ in range(20)]
print(cities)
cities_probs = [1.0/(i+1) for i in range(20)]
cities_probs_norm =  [float(i)/sum(cities_probs) for i in cities_probs]
print(cities_probs_norm)

['North Judithbury', 'East Jill', 'New Roberttown', 'East Jessetown', 'Lake Debra', 'Robinsonshire', 'Lisatown', 'Lake Roberto', 'Ericmouth', 'North Noahstad', 'Cassandraton', 'Herrerafurt', 'New Kellystad', 'Lake Chad', 'Port Keith', 'Port Jesseville', 'Ramirezstad', 'West Michael', 'Jacquelineland', 'New Jessica']
[0.2779522965244017, 0.13897614826220084, 0.09265076550813389, 0.06948807413110042, 0.055590459304880345, 0.046325382754066946, 0.039707470932057384, 0.03474403706555021, 0.0308835885027113, 0.027795229652440172, 0.025268390593127427, 0.023162691377033473, 0.02138094588649244, 0.019853735466028692, 0.01853015310162678, 0.017372018532775105, 0.01635013508967069, 0.01544179425135565, 0.014629068238126404, 0.013897614826220086]

In [9]:
good_companies = [fake.company() for _ in range(50)]
bad_companies = [fake.company() for _ in range(30)]

In [10]:

for i in df.index:
    
    # Age
    days = df.loc[i, 'Age']*365 + (random.randrange(365*2) - 365)
    dob = today - datetime.timedelta(days=int(days))
    df.at[i, 'DateOfBirth'] = dob
    
    if df.loc[i, 'Personal.Male.Divorced.Seperated'] == 1 or df.loc[i, 'Personal.Male.Single'] == 1 or df.loc[i, 'Personal.Male.Married.Widowed'] == 1:
        df.at[i, 'Sex'] = "M"
        df.at[i, 'FirstName'] = fake.first_name_male()
    else:
        df.at[i, 'Sex'] = "F"
        df.at[i, 'FirstName'] = fake.first_name_female()
        
    df.at[i, 'LastName'] = fake.last_name()
        
    if df.loc[i, 'Personal.Male.Married.Widowed'] == 1 or df.loc[i, 'Personal.Female.NotSingle'] == 1:
        df.at[i, 'Married'] = int(1)
    else:
        df.at[i, 'Married'] = int(0)
    

    # Nonsense feature
    df.loc[i, 'NumberPets'] = random.randrange(3)
    
    if df.loc[i, 'EmploymentDuration.lt.1'] == 1:
        df.at[i, 'EmploymentDuration'] = 0
    elif df.loc[i, 'EmploymentDuration.1.to.4'] == 1:
        df.at[i, 'EmploymentDuration'] = 1 + random.randrange(4)
    elif df.loc[i, 'EmploymentDuration.4.to.7'] == 1:
        df.at[i, 'EmploymentDuration'] = 4 + random.randrange(4)
    elif df.loc[i, 'EmploymentDuration.gt.7'] == 1:
        df.at[i, 'EmploymentDuration'] = 7 + random.randrange(10)
        
    if df.loc[i, 'SavingsAccountBonds.Unknown'] == 1:
        df.at[i, 'SavingsAccountBonds'] = random.randrange(600)
    elif df.loc[i, 'SavingsAccountBonds.lt.100'] == 1:
        df.at[i, 'SavingsAccountBonds'] = 0
    elif df.loc[i, 'SavingsAccountBonds.100.to.500'] == 1:
        df.at[i, 'SavingsAccountBonds'] = 100 + random.randrange(401)
    elif df.loc[i, 'SavingsAccountBonds.500.to.1000'] == 1:
        df.at[i, 'SavingsAccountBonds'] = 500 + random.randrange(501)
    elif df.loc[i, 'SavingsAccountBonds.gt.1000'] == 1:
        df.at[i, 'SavingsAccountBonds'] = 1000 + random.randrange(1000)
        
        
    inflation = 1.8
    
    df.at[i, 'Amount'] = round(df.loc[i, 'Amount'] * inflation)
    
   
    df.at[i, 'Street'] = fake.street_address()
    #df.at[i, 'City'] = fake.city()
    
    df.at[i, "LicensePlate"] = fake.license_plate()
    
    df.at[i, 'UserID'] = fake.ssn()
    
df['City'] = random.choices(cities, cities_probs_norm, k=df.shape[0])

In [11]:
df = df.drop(['Age'], axis=1)
df = df.rename(columns={'Telephone': 'OwnCar', 'Class': "Credit"})
df = df[df.columns.drop(list(df.filter(regex='Personal.')))]
df = df[df.columns.drop(list(df.filter(regex='EmploymentDuration.')))]
df = df[df.columns.drop(list(df.filter(regex='SavingsAccountBonds.')))]

In [12]:
df['BadCredit'] = df['Credit'].apply(lambda x: 0 if x == 'Good' else 1)
df = df.drop('Credit', axis=1)

In [13]:
front_cols = ['UserID', 'FirstName', 'LastName', 'DateOfBirth', 'Sex', 'Street', 'City', 'LicensePlate', 'Married', "NumberPets"]

df = df[ front_cols + [ col for col in df.columns if col not in front_cols] ]

last_cols = ['BadCredit']
df = df[ [ col for col in df.columns if col not in last_cols] + last_cols ]

In [14]:
df.head()

,UserID,FirstName,LastName,DateOfBirth,Sex,Street,City,LicensePlate,Married,NumberPets,...,Housing.Rent,Housing.Own,Housing.ForFree,Job.UnemployedUnskilled,Job.UnskilledResident,Job.SkilledEmployee,Job.Management.SelfEmp.HighlyQualified,EmploymentDuration,SavingsAccountBonds,BadCredit
0,216-88-4089,Christopher,Ramos,1953-09-02,M,011 Amy Village Suite 982,North Judithbury,0-E4505,0.0,0.0,...,0,1,0,0,0,1,0,7.0,281.0,0
1,880-61-3645,Mary,Gomez,1999-09-30,F,232 Nicole Burg Apt. 563,East Jill,160F,1.0,0.0,...,0,1,0,0,0,1,0,2.0,0.0,1
2,183-75-4350,Curtis,Sellers,1973-03-01,M,3303 Murphy Way Apt. 458,West Michael,VR1 K4A,0.0,2.0,...,0,1,0,0,1,0,0,4.0,0.0,0
3,681-43-5144,Andrew,Carlson,1975-10-17,M,569 Paul Ports Apt. 406,North Judithbury,8QZ3561,0.0,1.0,...,0,0,1,0,0,1,0,4.0,0.0,0
4,416-71-0007,Matthew,Martinez,1969-05-15,M,465 Terry Plaza Apt. 366,Ramirezstad,299X4,0.0,0.0,...,0,0,1,0,0,1,0,2.0,0.0,1

In [15]:
df['BadCredit'].value_counts()

0    700
1    300
Name: BadCredit, dtype: int64

In [16]:
df.to_csv('generated_german.csv', index=False)

# Now make a not-OHE version

In [17]:
df2 = df.copy(deep=True)

In [18]:
df2.head().T

,0,1,2,3,4
UserID,216-88-4089,880-61-3645,183-75-4350,681-43-5144,416-71-0007
FirstName,Christopher,Mary,Curtis,Andrew,Matthew
LastName,Ramos,Gomez,Sellers,Carlson,Martinez
DateOfBirth,1953-09-02,1999-09-30,1973-03-01,1975-10-17,1969-05-15
Sex,M,F,M,M,M
Street,011 Amy Village Suite 982,232 Nicole Burg Apt. 563,3303 Murphy Way Apt. 458,569 Paul Ports Apt. 406,465 Terry Plaza Apt. 366
City,North Judithbury,East Jill,West Michael,North Judithbury,Ramirezstad
LicensePlate,0-E4505,160F,VR1 K4A,8QZ3561,299X4
Married,0,1,0,0,0
NumberPets,0,0,2,1,0
Duration,6,48,12,42,24
Amount,2104,10712,3773,14188,8766
InstallmentRatePercentage,4,2,2,2,3
ResidenceDuration,4,2,3,4,4
NumberExistingCredits,2,1,1,1,2
NumberPeopleMaintenance,1,1,2,2,2
OwnCar,0,1,1,1,1
ForeignWorker,1,1,1,1,1
CheckingAccountStatus.lt.0,1,0,0,1,1
CheckingAccountStatus.0.to.200,0,1,0,0,0
CheckingAccountStatus.gt.200,0,0,0,0,0
CheckingAccountStatus.none,0,0,1,0,0
CreditHistory.NoCredit.AllPaid,0,0,0,0,0
CreditHistory.ThisBank.AllPaid,0,0,0,0,0
CreditHistory.PaidDuly,0,1,0,1,0
CreditHistory.Delay,0,0,0,0,1
CreditHistory.Critical,1,0,1,0,0
Purpose.NewCar,0,0,0,0,1
Purpose.UsedCar,0,0,0,0,0
Purpose.Furniture.Equipment,0,0,0,1,0
Purpose.Radio.Television,1,1,0,0,0
Purpose.DomesticAppliance,0,0,0,0,0
Purpose.Repairs,0,0,0,0,0
Purpose.Education,0,0,1,0,0
Purpose.Vacation,0,0,0,0,0
Purpose.Retraining,0,0,0,0,0
Purpose.Business,0,0,0,0,0
Purpose.Other,0,0,0,0,0
OtherDebtorsGuarantors.None,1,1,1,0,1
OtherDebtorsGuarantors.CoApplicant,0,0,0,0,0
OtherDebtorsGuarantors.Guarantor,0,0,0,1,0
Property.RealEstate,1,1,1,0,0
Property.Insurance,0,0,0,1,0
Property.CarOther,0,0,0,0,0
Property.Unknown,0,0,0,0,1
OtherInstallmentPlans.Bank,0,0,0,0,0
OtherInstallmentPlans.Stores,0,0,0,0,0
OtherInstallmentPlans.None,1,1,1,1,1
Housing.Rent,0,0,0,0,0
Housing.Own,1,1,1,0,0
Housing.ForFree,0,0,0,1,1
Job.UnemployedUnskilled,0,0,0,0,0
Job.UnskilledResident,0,0,1,0,0
Job.SkilledEmployee,1,1,0,1,1
Job.Management.SelfEmp.HighlyQualified,0,0,0,0,0
EmploymentDuration,7,2,4,4,2
SavingsAccountBonds,281,0,0,0,0
BadCredit,0,1,0,0,1

In [19]:
df2['Married'] = df2['Married'].map({0:'no', 1:'yes'})
df2['OwnCar'] = df2['OwnCar'].map({0:'no', 1:'yes'})
df2['ForeignWorker'] = df2['ForeignWorker'].map({0:'no', 1:'yes'})

In [20]:
for t in ['Purpose', 'Property', 'Job', 'Housing', 'OtherDebtorsGuarantors', 'CreditHistory', 'CheckingAccountStatus', 'OtherInstallmentPlans']:
  cols = [c for c in df2.columns.tolist() if t in c]
  df2[t] = df2[cols].idxmax(axis=1)
  df2 = df2.drop(cols, axis=1)

In [21]:
import random

def choose_city(x):
    thresh = 0.2
    if x['BadCredit'] == 0:
        thresh = 0.8
    
    if random.uniform(0, 1) < thresh:
        return random.choice(good_companies)
    else:
        return random.choice(bad_companies)
        
df2['Company'] = df2.apply(choose_city, axis=1)

In [22]:
df2.head().T

,0,1,2,3,4
UserID,216-88-4089,880-61-3645,183-75-4350,681-43-5144,416-71-0007
FirstName,Christopher,Mary,Curtis,Andrew,Matthew
LastName,Ramos,Gomez,Sellers,Carlson,Martinez
DateOfBirth,1953-09-02,1999-09-30,1973-03-01,1975-10-17,1969-05-15
Sex,M,F,M,M,M
Street,011 Amy Village Suite 982,232 Nicole Burg Apt. 563,3303 Murphy Way Apt. 458,569 Paul Ports Apt. 406,465 Terry Plaza Apt. 366
City,North Judithbury,East Jill,West Michael,North Judithbury,Ramirezstad
LicensePlate,0-E4505,160F,VR1 K4A,8QZ3561,299X4
Married,no,yes,no,no,no
NumberPets,0,0,2,1,0
Duration,6,48,12,42,24
Amount,2104,10712,3773,14188,8766
InstallmentRatePercentage,4,2,2,2,3
ResidenceDuration,4,2,3,4,4
NumberExistingCredits,2,1,1,1,2
NumberPeopleMaintenance,1,1,2,2,2
OwnCar,no,yes,yes,yes,yes
ForeignWorker,yes,yes,yes,yes,yes
EmploymentDuration,7,2,4,4,2
SavingsAccountBonds,281,0,0,0,0
BadCredit,0,1,0,0,1
Purpose,Purpose.Radio.Television,Purpose.Radio.Television,Purpose.Education,Purpose.Furniture.Equipment,Purpose.NewCar
Property,Property.RealEstate,Property.RealEstate,Property.RealEstate,Property.Insurance,Property.Unknown
Job,Job.SkilledEmployee,Job.SkilledEmployee,Job.UnskilledResident,Job.SkilledEmployee,Job.SkilledEmployee
Housing,Housing.Own,Housing.Own,Housing.Own,Housing.ForFree,Housing.ForFree
OtherDebtorsGuarantors,OtherDebtorsGuarantors.None,OtherDebtorsGuarantors.None,OtherDebtorsGuarantors.None,OtherDebtorsGuarantors.Guarantor,OtherDebtorsGuarantors.None
CreditHistory,CreditHistory.Critical,CreditHistory.PaidDuly,CreditHistory.Critical,CreditHistory.PaidDuly,CreditHistory.Delay
CheckingAccountStatus,CheckingAccountStatus.lt.0,CheckingAccountStatus.0.to.200,CheckingAccountStatus.none,CheckingAccountStatus.lt.0,CheckingAccountStatus.lt.0
OtherInstallmentPlans,OtherInstallmentPlans.None,OtherInstallmentPlans.None,OtherInstallmentPlans.None,OtherInstallmentPlans.None,OtherInstallmentPlans.None
Company,Harrell LLC,"Ferrell, Jones and Lewis",George Group,"West, Henderson and Ramirez","Sanchez, Wheeler and Harvey"

In [23]:
df2.to_csv('generated_german_cat.csv', index=False)